# Generated by Django 2.1.7 on 2019-04-08 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='QuestionTemplate',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizLog',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
