# Generated by Django 2.1.7 on 2019-04-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190408_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course_ids',
        ),
        migrations.AddField(
            model_name='quiz',
            name='course_id',
            field=models.IntegerField(null=True),
        ),
    ]
