# Generated by Django 2.1.7 on 2019-04-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190409_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
