# Generated by Django 2.1.7 on 2019-04-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20190409_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlog',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizlog',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
