# Generated by Django 2.1.7 on 2019-03-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0002_auto_20190327_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('question_json', models.TextField()),
                ('course_ids', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='datetime',
            new_name='created_on',
        ),
    ]
