# Generated by Django 2.1.7 on 2019-03-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0003_auto_20190327_2218'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quiz',
            table='quizes',
        ),
    ]
