# Generated by Django 2.1.7 on 2019-03-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0005_auto_20190327_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('hashes_json', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('hashes_json', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'question_templates',
            },
        ),
        migrations.CreateModel(
            name='QuizLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_hash', models.CharField(max_length=255)),
                ('quiz_id', models.IntegerField(null=True)),
                ('results_json', models.TextField(null=True)),
                ('num_questions', models.IntegerField(null=True)),
                ('num_incorrect', models.IntegerField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'quiz_logs',
            },
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_json',
            field=models.TextField(null=True),
        ),
    ]
